version: '3.7'
services:
  server:
    environment:
      - MONGO_URI_TEST=mongodb://mongodb:27017/devstest
      - MONGO_URI=mongodb://mongodb:27017/devs
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crudserver
    ports:
        - 3333:3333
    depends_on:
        - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - 27017:27017
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true